name: storyreader
description: A multimedia story reader application with synchronized media grids

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  
  # File Handling
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Document Parsing
  pdf: ^3.10.4
  html: ^0.15.4
  docx_to_text: ^0.4.0
  
  # Media Handling
  video_player: ^2.7.2
  image: ^4.1.3
  
  # Grid Layout
  flutter_staggered_grid_view: ^0.7.0
  
  # Storage & Serialization
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  
  # Archive/Packaging
  archive: ^3.4.8
  
  # Auto Scroll
  auto_scroll_text: ^0.2.0
  
  # UI Components
  flutter_colorpicker: ^1.0.3
  
  # Multi-platform
  desktop_window: ^0.4.0
  window_manager: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/CustomFont-Regular.ttf
        - asset: assets/fonts/CustomFont-Bold.ttf
          weight: 700